(function(){
  "use strict";
  const D=window.PROTOTYPE_DATA;
  const S={role:"business",page:"dashboard",filter:"全部",reviewId:D.reviewQueue[0].id};
  const $=(q,root=document)=>root.querySelector(q);
  const icons={
    dashboard:'<svg viewBox="0 0 24 24"><path d="M4 13h6V4H4v9Zm0 7h6v-4H4v4Zm10 0h6v-9h-6v9Zm0-16v4h6V4h-6Z"/></svg>',
    list:'<svg viewBox="0 0 24 24"><path d="M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01"/></svg>',
    review:'<svg viewBox="0 0 24 24"><path d="M9 11 11 13 15.5 8.5M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z"/></svg>',
    qr:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h2v2h-2v-2Zm4 0h2v2h-2v-2Zm-4 4h2v2h-2v-2Zm4 0h2v2h-2v-2Z"/></svg>',
    approval:'<svg viewBox="0 0 24 24"><path d="M7 3h10v4H7V3ZM5 5H3v16h18V5h-2M7 12h10M7 16h6"/></svg>',
    verify:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm11 1 2 2 4-5"/></svg>',
    site:'<svg viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>',
    content:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5V3Zm4 5h6M9 12h6M9 16h4"/></svg>',
    users:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
    shield:'<svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Zm-3-10 2 2 4-4"/></svg>',
    settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.1A1.7 1.7 0 0 0 8 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 3.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H2V9.6h.1A1.7 1.7 0 0 0 3.6 8a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 8 3.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V2h4v.1A1.7 1.7 0 0 0 15 3.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 8c.15.4.4.75.76 1 .3.25.7.4 1.1.4H21v4h-.1a1.7 1.7 0 0 0-1.5 1.6Z"/></svg>',
    log:'<svg viewBox="0 0 24 24"><path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5M12 7v5l3 2"/></svg>',
    search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
    close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>',
    info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg>',
    check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
    export:'<svg viewBox="0 0 24 24"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"/></svg>'
  };
  const pageMeta={dashboard:["业务工作台","工作台 / 业务概览"],registrations:["运送登记管理","业务管理 / 运送登记"],review:["照片与定位审核","业务管理 / 审核工作台"],codes:["处置码管理","业务管理 / 处置码"],extensions:["延期审批","业务管理 / 处置码 / 延期审批"],verifications:["核销记录","业务管理 / 核销管理"],sites:["堆放点管理","资源管理 / 堆放点"],content:["内容管理","运营管理 / 内容"],users:["用户管理","组织管理 / 小程序用户"],permissions:["角色权限","组织管理 / 权限"],settings:["业务规则配置","系统管理 / 业务规则"],logs:["操作日志","系统管理 / 操作日志"]};
  const navGroups=[
    ["业务总览",[["dashboard","工作台","dashboard"]]],
    ["业务管理",[["registrations","运送登记","list"],["review","照片定位审核","review"],["codes","处置码管理","qr"],["extensions","延期审批","approval"],["verifications","核销记录","verify"]]],
    ["运营管理",[["sites","堆放点管理","site"],["content","内容管理","content"],["users","用户管理","users"]]],
    ["系统管理",[["permissions","角色权限","shield"],["settings","业务规则","settings"],["logs","操作日志","log"]]]
  ];
  function renderNav(){const allowed=D.roles[S.role].pages;$("#main-nav").innerHTML=navGroups.map(([label,items])=>{const visible=items.filter(i=>allowed.includes(i[0]));return visible.length?`<div class="nav-group"><span class="nav-label">${label}</span>${visible.map(([id,name,icon])=>`<button class="nav-item ${id===S.page?'active':''}" data-page="${id}">${icons[icon]}<span>${name}</span>${id==='extensions'&&S.role!=='reviewer'?'<span class="nav-badge">3</span>':''}</button>`).join('')}</div>`:''}).join('')}
  function tag(v){const m={"已核销":"success","正常":"success","已通过":"success","启用":"success","已发布":"success","成功":"success","查看":"success","待核销":"info","管理":"info","待审核":"warning","待审批":"warning","草稿":"warning","审核":"warning","即将失效":"warning","已失效":"danger","已退回":"danger","异常":"danger","越界":"danger","疑似越界":"warning","疑似异常":"warning","停用":"danger","封禁":"danger","已下线":"danger","作废":""};return `<span class="tag ${m[v]||''}">${v}</span>`}
  function pageIntro(title,desc,actions=''){return `<div class="page-intro"><div><h2>${title}</h2><p>${desc}</p></div><div class="page-actions">${actions}</div></div>`}
  function filterBar(extra=''){return `<div class="filter-panel"><div class="field grow"><label>关键词</label><input class="input" id="keyword" placeholder="处置码、登记人、手机号或地址"></div><div class="field"><label>业务状态</label><select class="select" id="status-filter"><option>全部</option><option>待核销</option><option>已核销</option><option>已退回</option><option>已失效</option><option>作废</option></select></div>${extra}<button class="button" data-action="filter">${icons.search}查询</button><button class="ghost-button" data-action="reset-filter">重置</button></div>`}
  function dashboard(){const r=S.role;const data=r==='reviewer'?[["待审核记录","18","较昨日 +4"],["定位异常","6","其中越界 2 条"],["今日已审核","27","平均 3.6 分钟"],["高风险待复核","3","需优先处理"]]:r==='system'?[["今日登记","86","较昨日 +12.4%"],["今日核销","54","核销率 62.8%"],["业务异常","9","3项高风险"],["系统待办","7","权限与配置"]]:[["今日登记","86","较昨日 +12.4%"],["待核销","32","6个即将失效"],["延期待审批","3","最长等待 2.1小时"],["退回与作废","7","较昨日 -2"]];return `<div class="page-enter">${pageIntro(`${D.roles[r].name}工作台`,r==='reviewer'?'聚焦照片真实性、定位一致性与疑似越界记录。':r==='system'?'掌握全局业务运行、系统配置与操作审计情况。':'优先处理待核销、延期、退回及用户异常。','<button class="ghost-button" data-action="refresh">刷新数据</button>')}<div class="role-note">${icons.info}<span>当前按<strong>${D.roles[r].name}</strong>展示菜单、指标和操作权限。可通过右上角切换角色演示差异。</span></div><div class="metrics-grid">${data.map((m,i)=>`<article class="metric ${i===0?'primary':''}"><div class="metric-label"><span>${m[0]}</span><span class="metric-icon">${icons[["list","verify","review","approval"][i]]}</span></div><div class="metric-value">${m[1]}</div><div class="metric-note"><span class="up">${m[2]}</span></div></article>`).join('')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><div><h3>近7日登记与核销趋势</h3><small>单位：车次 · 按提交日期与核销完成日期统计</small></div><div class="legend"><span>登记</span><span>核销</span></div></div><div class="panel-body"><div class="chart">${[52,64,58,79,73,91,86].map((v,i)=>`<div class="bar-wrap"><div class="bar" style="height:${v}%"></div><div class="bar alt" style="height:${Math.max(30,v-22)}%"></div><label>${7+i}日</label></div>`).join('')}</div></div></section><section class="panel"><div class="panel-header"><div><h3>${r==='reviewer'?'审核优先队列':'今日优先任务'}</h3><small>按风险与时效排序</small></div></div><div class="panel-body"><div class="task-list">${taskList(r)}</div><div class="risk-list"><div class="risk-item"><span class="risk-dot"></span><div><b>3条高风险记录待处理</b><small>照片疑似非实时、定位越界</small></div><button class="link-button" data-page="review">查看</button></div><div class="risk-item"><span class="risk-dot"></span><div><b>6个处置码将在6小时内失效</b><small>建议联系用户或审批延期</small></div><button class="link-button" data-page="codes">查看</button></div></div></div></section></div></div>`}
  function taskList(role){const x=role==='reviewer'?[["待审核照片",18,"review"],["疑似定位异常",6,"review"],["审核退回复核",3,"review"]]:role==='system'?[["异常业务记录",9,"review"],["待处理账号",2,"permissions"],["配置变更复核",5,"logs"]]:[["延期待审批",3,"extensions"],["待核销记录",32,"registrations"],["用户异常",4,"users"]];return x.map(([t,n,p])=>`<button class="task" data-page="${p}"><span class="task-icon">${icons.approval}</span><span><b>${t}</b><small>点击进入处理列表</small></span><strong>${n}</strong></button>`).join('')}
  function registrationRows(rows){return rows.map(r=>`<tr><td><span class="code">${r.code}</span><br><span class="muted">${r.id}</span></td><td>${r.user}<br><span class="muted">${r.phone}</span></td><td>${r.address}</td><td>${r.time}</td><td>${r.expire}</td><td>${tag(r.photo)} / ${tag(r.location)}</td><td>${tag(r.status)}</td><td><div class="row-actions"><button class="link-button" data-action="registration-detail" data-id="${r.id}">详情</button>${S.role!=='reviewer'&&r.status==='待核销'?`<button class="link-button" data-action="void" data-id="${r.id}">作废</button>`:''}</div></td></tr>`).join('')}
  function registrations(){return `<div class="page-enter">${pageIntro('运送登记管理','承接小程序提交的三张照片、定位和处置码数据，后台以查询、审核和追溯为主。','<button class="ghost-button" data-action="export">'+icons.export+'导出列表</button>')}${filterBar('<div class="field"><label>提交时间</label><input class="input" type="date" value="2026-07-13"></div>')}<section class="table-panel"><div class="panel-header"><div><h3>登记记录</h3><small>共 186 条 · 当前展示模拟数据</small></div><span class="tag info">作废操作全程留痕</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>处置码 / 登记编号</th><th>登记人</th><th>垃圾来源</th><th>提交时间</th><th>有效期至</th><th>照片 / 定位</th><th>状态</th><th>操作</th></tr></thead><tbody id="registration-body">${registrationRows(D.registrations)}</tbody></table></div>${pagination()}</section></div>`}
  function pagination(){return `<div class="pagination"><span>第 1–7 条，共 186 条</span><div class="pager"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div>`}
  function review(){const item=D.reviewQueue.find(i=>i.id===S.reviewId)||D.reviewQueue[0];const record=D.registrations.find(r=>r.id===item.id)||D.registrations[0];return `<div class="page-enter">${pageIntro('照片与定位审核','审核采用事后抽查机制，不阻塞现场正常核销；高风险记录进入优先队列。','<span class="tag info">规则自动预检 + 人工复核</span>')}<div class="review-layout"><section class="panel"><div class="panel-header"><div><h3>待审核队列</h3><small>按风险等级和提交时间排序</small></div><span class="tag danger">3 条高风险</span></div><div class="panel-body"><div class="review-queue">${D.reviewQueue.map(i=>`<button class="review-card ${i.id===item.id?'active':''}" data-action="select-review" data-id="${i.id}"><span class="thumb"></span><span><b>${i.title}</b><small>${i.id} · ${i.meta}</small></span>${tag(i.risk==='高'?'异常':'待审核')}</button>`).join('')}</div></div></section><section class="panel"><div class="panel-header"><div><h3>审核处理</h3><small>${record.code}</small></div></div><div class="panel-body"><div class="photo-grid"><div class="photo"><span>空车照片 · 09:11</span></div><div class="photo"><span>现场垃圾 · 09:13</span></div><div class="photo"><span>装车照片 · 09:16</span></div></div><div class="map-box" style="margin-top:12px"><div class="map-road"></div><i class="map-pin one"></i><i class="map-pin two"></i><i class="map-pin three"></i></div><div class="confirm-note" style="margin-top:12px">系统提示：装车定位距垃圾产生地 4.7 km，超过相邻拍摄点 500 m 阈值，已进入高风险复核队列。</div><div class="field"><label>审核备注</label><textarea class="textarea" id="review-note" placeholder="填写审核判断依据"></textarea></div><div class="page-actions" style="margin-top:12px"><button class="ghost-button" data-action="review-pass">标记正常</button><button class="button warning" data-action="review-risk">标记异常</button></div></div></section></div></div>`}
  function codes(){return `<div class="page-enter">${pageIntro('处置码管理','查看小程序登记生成的处置码，管理有效期、延期和作废状态。','<span class="tag info">一单一码 · 有效期2天</span>')}${filterBar()}<section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>处置码</th><th>关联登记</th><th>登记人</th><th>生成时间</th><th>有效期至</th><th>状态</th><th>延期状态</th><th>操作</th></tr></thead><tbody>${D.registrations.slice(0,6).map(r=>`<tr><td class="code">${r.code}</td><td>${r.id}</td><td>${r.user}</td><td>${r.time}</td><td>${r.expire}</td><td>${tag(r.status)}</td><td>${r.status==='即将失效'?tag('待审批'):'—'}</td><td><button class="link-button" data-action="registration-detail" data-id="${r.id}">查看</button></td></tr>`).join('')}</tbody></table></div>${pagination()}</section></div>`}
  function extensions(){return `<div class="page-enter">${pageIntro('延期审批','处置码到期前可申请延期，每个处置码限申请1次，审批通过后延长1天。','<span class="tag info">到期前申请 · 限1次 · 延长1天</span>')}<section class="table-panel"><div class="panel-header"><div><h3>延期申请</h3><small>待审批 1 条</small></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>申请编号</th><th>处置码</th><th>申请人</th><th>原有效期</th><th>申请延期</th><th>申请原因</th><th>状态</th><th>操作</th></tr></thead><tbody>${D.extensionRequests.map(r=>`<tr><td class="code">${r.id}</td><td class="code">${r.code}</td><td>${r.applicant}</td><td>${r.original}</td><td>${r.days} 天</td><td>${r.reason}</td><td>${tag(r.status)}</td><td>${r.status==='待审批'?`<button class="link-button" data-action="extension" data-result="approve" data-id="${r.id}">审批</button>`:'<button class="link-button">记录</button>'}</td></tr>`).join('')}</tbody></table></div></section></div>`}
  function verifications(){return `<div class="page-enter">${pageIntro('核销记录','查看小程序端核销员扫码产生的核销与退回结果；后台只负责查询、追溯与统计。','<span class="tag info">退回后须重新登记</span>')}${filterBar()}<section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>核销编号</th><th>处置码</th><th>处置联单编号</th><th>核销员</th><th>扫码时间</th><th>完成时间</th><th>堆放点</th><th>状态</th><th>操作</th></tr></thead><tbody>${D.verifications.map(r=>`<tr><td class="code">${r.id}</td><td class="code">${r.code}</td><td>${r.form}</td><td>${r.verifier}</td><td>${r.scan}</td><td>${r.verified}</td><td>${r.site}</td><td>${tag(r.status)}</td><td><button class="link-button" data-action="verification-detail" data-id="${r.id}">详情</button></td></tr>`).join('')}</tbody></table></div></section></div>`}
  function sites(){return `<div class="page-enter">${pageIntro('堆放点管理','维护小程序服务须知展示的地址、开放时间、联系人和启停状态。','<button class="button" data-action="site-add">新增堆放点</button>')}<section class="table-panel"><div class="panel-header"><div><h3>堆放点列表</h3><small>启用 1 个 · 停用 1 个</small></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>堆放点</th><th>地址</th><th>所属区域</th><th>开放时间</th><th>联系人</th><th>联系电话</th><th>状态</th><th>操作</th></tr></thead><tbody>${D.sites.map(r=>`<tr><td><b>${r.name}</b><br><span class="code">${r.id}</span></td><td>${r.address}</td><td>${r.area}</td><td>${r.hours}</td><td>${r.contact}</td><td>${r.phone}</td><td>${tag(r.status)}</td><td><button class="link-button" data-action="site-edit" data-id="${r.id}">编辑</button><button class="link-button" data-action="site-toggle" data-id="${r.id}">${r.status==='启用'?'停用':'启用'}</button></td></tr>`).join('')}</tbody></table></div></section></div>`}
  function content(){return `<div class="page-enter">${pageIntro('内容管理','统一维护小程序首页宣传、办理指南、备案指南、服务须知和温馨提示。','<button class="button" data-action="content-edit">新建内容</button>')}<div class="metrics-grid compact-metrics"><article class="metric primary"><div class="metric-label"><span>已发布内容</span><span class="metric-icon">${icons.content}</span></div><div class="metric-value">3</div><div class="metric-note">覆盖 5 类内容栏目</div></article><article class="metric"><div class="metric-label"><span>草稿</span></div><div class="metric-value">1</div><div class="metric-note">今日 09:35 更新</div></article><article class="metric"><div class="metric-label"><span>已下线</span></div><div class="metric-value">1</div><div class="metric-note">可查看历史版本</div></article><article class="metric"><div class="metric-label"><span>本月发布</span></div><div class="metric-value">7</div><div class="metric-note">较上月增加 2 篇</div></article></div><section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>内容类型</th><th>标题</th><th>版本</th><th>更新人</th><th>更新时间</th><th>发布状态</th><th>操作</th></tr></thead><tbody>${D.contents.map(r=>`<tr><td>${tag(r.type)}</td><td><b>${r.title}</b><br><span class="code">${r.id}</span></td><td>${r.version}</td><td>${r.editor}</td><td>${r.updated}</td><td>${tag(r.status)}</td><td><button class="link-button" data-action="content-edit" data-id="${r.id}">编辑</button>${r.status==='草稿'?'<button class="link-button" data-action="content-publish">发布</button>':r.status==='已发布'?'<button class="link-button" data-action="content-offline">下线</button>':'<button class="link-button" data-action="content-edit">重新编辑</button>'}</td></tr>`).join('')}</tbody></table></div></section></div>`}
  function users(){return `<div class="page-enter">${pageIntro('用户管理','查看小程序用户、业务记录、异常情况及账号状态。','<button class="ghost-button" data-action="export">'+icons.export+'导出用户</button>')}<div class="filter-panel"><div class="field grow"><label>用户关键词</label><input class="input" placeholder="姓名、手机号或用户编号"></div><div class="field"><label>账号状态</label><select class="select"><option>全部</option><option>正常</option><option>封禁</option></select></div><button class="button" data-action="mock-search">${icons.search}查询</button></div><section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>用户</th><th>手机号</th><th>注册时间</th><th>登记次数</th><th>异常次数</th><th>最近使用</th><th>状态</th><th>操作</th></tr></thead><tbody>${D.users.map(r=>`<tr><td><b>${r.name}</b><br><span class="code">${r.id}</span></td><td>${r.phone}</td><td>${r.registered}</td><td>${r.records}</td><td>${r.abnormal?`<span class="tag ${r.abnormal>1?'danger':'warning'}">${r.abnormal} 次</span>`:'0'}</td><td>${r.last}</td><td>${tag(r.status)}</td><td><button class="link-button" data-action="user-detail" data-id="${r.id}">详情</button><button class="link-button" data-action="user-toggle" data-id="${r.id}">${r.status==='正常'?'封禁':'解封'}</button></td></tr>`).join('')}</tbody></table></div></section></div>`}
  function permissions(){const rows=[['工作台','查看','查看','查看'],['运送登记','管理','管理','查看'],['照片定位审核','管理','管理','审核'],['处置码与延期','管理','管理','查看'],['核销记录','管理','查看','查看'],['堆放点与内容','管理','管理','无'],['用户管理','管理','管理','无'],['角色权限','管理','无','无'],['业务规则与日志','管理','无','无']];return `<div class="page-enter">${pageIntro('角色权限','按系统管理员、业务管理员和审核人员配置菜单、操作与数据范围。','<button class="button" data-action="save-permissions">保存权限配置</button>')}<div class="settings-grid"><section class="panel"><div class="panel-header"><div><h3>角色数据范围</h3><small>当前为基础权限方案</small></div></div><div class="panel-body"><div class="permission-summary"><div><b>系统管理员</b><span>全部区域、全部数据</span></div><div><b>业务管理员</b><span>全部或授权区域业务数据</span></div><div><b>审核人员</b><span>仅授权区域，审核相关数据</span></div></div></div></section><section class="panel"><div class="panel-header"><div><h3>权限说明</h3><small>管理 / 审核 / 查看 / 无</small></div></div><div class="panel-body"><p class="muted">系统管理员拥有全局权限；高风险操作包括角色变更、规则配置、作废和用户封禁，均记录操作日志。</p></div></section></div><section class="table-panel" style="margin-top:16px"><div class="table-scroll"><table class="data-table permission-table"><thead><tr><th>功能模块</th><th>系统管理员</th><th>业务管理员</th><th>审核人员</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td>${i?tag(v):`<b>${v}</b>`}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div>`}
  function settings(){return `<div class="page-enter">${pageIntro('业务规则配置','维护处置码、延期、照片定位和服务区域的全局业务规则。','<button class="button" data-action="save-settings">保存并生效</button>')}<div class="settings-grid"><section class="panel"><div class="panel-header"><div><h3>处置码规则</h3><small>影响新生成的处置码</small></div></div><div class="panel-body form-grid"><div class="field"><label>默认有效期</label><div class="input-unit"><input class="input" value="2"><span>天</span></div></div><div class="field"><label>到期预警时间</label><div class="input-unit"><input class="input" value="6"><span>小时</span></div></div><div class="field"><label>最大延期次数</label><div class="input-unit"><input class="input" value="1"><span>次</span></div></div><div class="field"><label>每次延长</label><div class="input-unit"><input class="input" value="1"><span>天</span></div></div></div></section><section class="panel"><div class="panel-header"><div><h3>照片与定位规则</h3><small>自动预检，异常进入人工审核</small></div></div><div class="panel-body form-grid"><div class="field"><label>拍摄总时长</label><div class="input-unit"><input class="input" value="120"><span>分钟</span></div></div><div class="field"><label>相邻点距离阈值</label><div class="input-unit"><input class="input" value="500"><span>米</span></div></div><div class="field"><label>GPS精度要求</label><div class="input-unit"><input class="input" value="100"><span>米内</span></div></div><div class="field"><label>审核机制</label><select class="select"><option>事后抽查</option><option>核销前置</option></select></div></div></section><section class="panel"><div class="panel-header"><div><h3>区域围栏</h3><small>垃圾产生地必须位于服务区域内</small></div></div><div class="panel-body"><div class="map-box"><div class="map-road"></div><i class="map-pin one"></i><i class="map-pin two"></i></div><div class="page-actions" style="margin-top:12px"><button class="ghost-button" data-action="mock-search">编辑服务区域</button><span class="tag success">围栏已启用</span></div></div></section><section class="panel"><div class="panel-header"><div><h3>规则生效策略</h3><small>避免影响已有业务记录</small></div></div><div class="panel-body"><label class="radio-line"><input type="radio" checked name="effective"> 仅对保存后新提交的登记生效</label><label class="radio-line"><input type="radio" name="effective"> 同时重新校验待核销记录</label><div class="confirm-note" style="margin-top:14px">规则修改后记录修改人、时间和变更内容，可在操作日志中追溯。</div></div></section></div></div>`}
  function logs(){return `<div class="page-enter">${pageIntro('操作日志','记录后台关键管理操作、业务审批和配置变更。','<button class="ghost-button" data-action="export">'+icons.export+'导出日志</button>')}<div class="filter-panel"><div class="field grow"><label>关键词</label><input class="input" placeholder="操作人、对象编号或动作"></div><div class="field"><label>功能模块</label><select class="select"><option>全部模块</option><option>延期审批</option><option>照片定位审核</option><option>业务规则</option></select></div><button class="button" data-action="mock-search">${icons.search}查询</button></div><section class="table-panel"><div class="table-scroll"><table class="data-table"><thead><tr><th>日志编号</th><th>操作人</th><th>角色</th><th>模块</th><th>操作动作</th><th>业务对象</th><th>操作时间</th><th>结果</th></tr></thead><tbody>${D.logs.map(r=>`<tr><td class="code">${r.id}</td><td>${r.user}</td><td>${r.role}</td><td>${r.module}</td><td>${r.action}</td><td class="code">${r.object}</td><td>${r.time}</td><td>${tag(r.result)}</td></tr>`).join('')}</tbody></table></div></section></div>`}
  const renderers={dashboard,registrations,review,codes,extensions,verifications,sites,content,users,permissions,settings,logs};
  function render(){const allowed=D.roles[S.role].pages;if(!allowed.includes(S.page))S.page='dashboard';renderNav();const meta=pageMeta[S.page];$('#page-title').textContent=meta[0];$('#breadcrumb').textContent=meta[1];$('#page-content').innerHTML=renderers[S.page]();$('#profile-name').textContent=D.roles[S.role].user;$('#profile-role').textContent=D.roles[S.role].name;$('#avatar').textContent=D.roles[S.role].avatar;$('#role-select').value=S.role;document.body.classList.remove('sidebar-open')}
  function registrationDrawer(id){const r=D.registrations.find(x=>x.id===id)||D.registrations[0];openDrawer(`<div class="drawer-header"><div><h2>运送登记详情</h2><p>${r.id} · ${r.code}</p></div><button class="icon-button" data-action="close-drawer" aria-label="关闭">${icons.close}</button></div><div class="drawer-content"><div class="detail-grid"><section class="detail-card full"><h3>基本信息</h3><div class="kv"><div><label>当前状态</label>${tag(r.status)}</div><div><label>登记人</label><span>${r.user} · ${r.phone}</span></div><div><label>垃圾来源</label><span>${r.address}</span></div><div><label>提交时间</label><span>${r.time}</span></div><div><label>有效期至</label><span>${r.expire}</span></div><div><label>到堆放点距离</label><span>${r.distance}</span></div></div></section><section class="detail-card full"><h3>现场照片</h3><div class="photo-grid"><div class="photo"><span>空车照片 · 自动定位</span></div><div class="photo"><span>现场垃圾 · 自动定位</span></div><div class="photo"><span>装车照片 · 自动定位</span></div></div></section><section class="detail-card"><h3>定位分析</h3><div class="map-box"><div class="map-road"></div><i class="map-pin one"></i><i class="map-pin two"></i><i class="map-pin three"></i></div></section><section class="detail-card"><h3>业务轨迹</h3><div class="timeline"><div class="timeline-item"><span class="timeline-mark"></span><div><b>提交登记并生成处置码</b><p>${r.time} · 小程序用户</p></div></div><div class="timeline-item"><span class="timeline-mark"></span><div><b>照片与定位规则检查</b><p>${r.photo} / ${r.location}</p></div></div><div class="timeline-item"><span class="timeline-mark"></span><div><b>${r.status==='已核销'?'现场核销完成':'等待现场核销'}</b><p>处置联单编号将在核销后记录</p></div></div></div></section></div></div><div class="drawer-footer"><button class="ghost-button" data-action="close-drawer">关闭</button><button class="button" data-page="review">进入审核</button></div>`)}
  function verificationDrawer(id){const r=D.verifications.find(x=>x.id===id);openDrawer(`<div class="drawer-header"><div><h2>核销记录详情</h2><p>${r.id}</p></div><button class="icon-button" data-action="close-drawer">${icons.close}</button></div><div class="drawer-content"><section class="detail-card"><h3>核销结果</h3><div class="kv"><div><label>状态</label>${tag(r.status)}</div><div><label>处置码</label><span class="code">${r.code}</span></div><div><label>联单编号</label><span>${r.form}</span></div><div><label>核销员</label><span>${r.verifier}</span></div><div><label>扫码时间</label><span>${r.scan}</span></div><div><label>完成时间</label><span>${r.verified}</span></div><div><label>堆放点</label><span>${r.site}</span></div></div></section>${r.status==='已退回'?'<div class="confirm-note" style="margin-top:14px">退回原因：现场装修垃圾与登记照片不一致。原处置码已终止，用户需重新完成运送登记并生成新码。</div>':''}</div><div class="drawer-footer"><button class="button" data-action="close-drawer">完成</button></div>`)}
  function openDrawer(html){$('#drawer').innerHTML=html;$('#drawer-mask').hidden=false}
  function closeDrawer(){$('#drawer-mask').hidden=true}
  function openModal(html){$('#modal').innerHTML=html;$('#modal-mask').hidden=false}
  function closeModal(){$('#modal-mask').hidden=true}
  function confirmModal(title,body,confirmText,action,kind=''){openModal(`<div class="modal-header"><h2>${title}</h2><button class="icon-button" data-action="close-modal">${icons.close}</button></div><div class="modal-content">${body}</div><div class="modal-footer"><button class="ghost-button" data-action="close-modal">取消</button><button class="button ${kind}" data-action="${action}">${confirmText}</button></div>`)}
  function toast(text){
    const el=document.createElement('div');
    el.className='toast';
    el.innerHTML=`${icons.check}<span>${text}</span>`;
    $('#toast-region').appendChild(el);
    setTimeout(()=>el.remove(),2800);
  }
  document.addEventListener('click',e=>{
    const t=e.target.closest('[data-page],[data-action]');
    if(!t)return;
    if(t.dataset.page){S.page=t.dataset.page;render();return;}
    const a=t.dataset.action;
    if(a==='toggle-sidebar')document.body.classList.toggle('sidebar-open');
    if(a==='close-drawer')closeDrawer();
    if(a==='close-modal')closeModal();
    if(a==='registration-detail')registrationDrawer(t.dataset.id);
    if(a==='verification-detail')verificationDrawer(t.dataset.id);
    if(a==='select-review'){S.reviewId=t.dataset.id;render();}
    if(a==='filter'){
      const kw=($('#keyword')?.value||'').trim();
      const st=$('#status-filter')?.value||'全部';
      const rows=D.registrations.filter(r=>(!kw||Object.values(r).join('').includes(kw))&&(st==='全部'||r.status===st));
      const body=$('#registration-body');
      if(body)body.innerHTML=rows.length?registrationRows(rows):`<tr><td colspan="8"><div class="empty">${icons.search}<h3>未找到匹配记录</h3><p>请调整关键词或状态条件后重试。</p></div></td></tr>`;
      toast(`已筛选出 ${rows.length} 条记录`);
    }
    if(a==='reset-filter'){if($('#keyword'))$('#keyword').value='';if($('#status-filter'))$('#status-filter').value='全部';render();}
    if(a==='export')toast('已生成模拟导出任务，本原型不会写入本地文件');
    if(a==='refresh')toast('工作台数据已刷新至 10:42');
    if(a==='void')confirmModal('确认作废处置码',`<div class="confirm-note">作废后不可恢复，且该处置码将无法继续核销。</div><div class="field"><label>作废原因</label><textarea class="textarea" id="void-reason" placeholder="请填写作废原因"></textarea><span class="helper">所有作废操作将进入操作日志</span></div>`,'确认作废','confirm-void','danger');
    if(a==='confirm-void'){
      const val=$('#void-reason')?.value.trim();
      if(!val){toast('请先填写作废原因');return;}
      closeModal();toast('处置码已模拟作废并记录操作日志');
    }
    if(a==='extension')confirmModal('审批延期申请',`<div class="confirm-note">每个处置码仅可延期 1 次，审批通过后有效期延长 1 天。</div><div class="form-grid"><div class="field"><label>审批结果</label><select class="select" id="extension-result"><option>通过</option><option>拒绝</option></select></div><div class="field"><label>延期天数</label><input class="input" value="1 天" disabled></div><div class="field full"><label>审批意见</label><textarea class="textarea" placeholder="填写审批意见"></textarea></div></div>`,'提交审批','confirm-extension');
    if(a==='confirm-extension'){closeModal();toast('延期审批结果已模拟提交');}
    if(a==='review-pass')toast('已标记为正常并进入审核记录');
    if(a==='review-risk')confirmModal('标记照片或定位异常',`<div class="form-grid"><div class="field"><label>异常类型</label><select class="select"><option>定位距离异常</option><option>疑似越界</option><option>照片非实时</option><option>照片内容不符</option></select></div><div class="field"><label>风险等级</label><select class="select"><option>中风险</option><option>高风险</option></select></div><div class="field full"><label>审核说明</label><textarea class="textarea" placeholder="请填写判断依据"></textarea></div></div>`,'确认标记','confirm-risk','warning');
    if(a==='confirm-risk'){closeModal();toast('已模拟标记异常，未自动封禁用户');}
    if(a==='site-add'||a==='site-edit'){
      const site=D.sites.find(x=>x.id===t.dataset.id)||{};
      confirmModal(site.id?'编辑堆放点':'新增堆放点',`<div class="form-grid"><div class="field full"><label>堆放点名称</label><input class="input" value="${site.name||''}" placeholder="输入名称"></div><div class="field full"><label>详细地址</label><input class="input" value="${site.address||''}" placeholder="输入地址"></div><div class="field"><label>所属区域</label><input class="input" value="${site.area||''}"></div><div class="field"><label>开放时间</label><input class="input" value="${site.hours||''}"></div><div class="field"><label>联系人</label><input class="input" value="${site.contact||''}"></div><div class="field"><label>联系电话</label><input class="input" value="${site.phone||''}"></div></div>`,'保存','confirm-site');
    }
    if(a==='confirm-site'){closeModal();toast('堆放点信息已模拟保存并同步小程序');}
    if(a==='site-toggle')confirmModal('变更堆放点状态',`<p>确认${t.textContent.trim()}该堆放点？状态变更后将同步影响小程序服务须知中的展示。</p>`,'确认变更','confirm-site-toggle');
    if(a==='confirm-site-toggle'){closeModal();toast('堆放点状态已模拟更新');}
    if(a==='content-edit'){
      const item=D.contents.find(x=>x.id===t.dataset.id)||{};
      confirmModal(item.id?'编辑内容':'新建内容',`<div class="form-grid"><div class="field"><label>内容类型</label><select class="select"><option>${item.type||'普法宣传'}</option><option>办理指南</option><option>备案指南</option><option>服务须知</option><option>温馨提示</option></select></div><div class="field"><label>发布状态</label><select class="select"><option>草稿</option><option>已发布</option></select></div><div class="field full"><label>标题</label><input class="input" value="${item.title||''}" placeholder="输入内容标题"></div><div class="field full"><label>正文</label><textarea class="textarea" placeholder="输入小程序展示内容">${item.title?'此处展示内容正文，支持分段和基础格式。':''}</textarea></div></div>`,'保存内容','confirm-content');
    }
    if(a==='confirm-content'){closeModal();toast('内容已模拟保存为新版本');}
    if(a==='content-publish')confirmModal('发布内容','<p>发布后内容将同步展示到小程序对应栏目，并保留当前历史版本。</p>','确认发布','confirm-publish');
    if(a==='confirm-publish'){closeModal();toast('内容已模拟发布并同步小程序');}
    if(a==='content-offline')confirmModal('下线内容','<p>下线后小程序将不再展示该内容，历史版本仍保留。</p>','确认下线','confirm-offline','warning');
    if(a==='confirm-offline'){closeModal();toast('内容已模拟下线');}
    if(a==='user-detail'){
      const u=D.users.find(x=>x.id===t.dataset.id);
      openDrawer(`<div class="drawer-header"><div><h2>小程序用户详情</h2><p>${u.id}</p></div><button class="icon-button" data-action="close-drawer">${icons.close}</button></div><div class="drawer-content"><div class="detail-grid"><section class="detail-card full"><h3>用户信息</h3><div class="kv"><div><label>用户姓名</label><span>${u.name}</span></div><div><label>手机号</label><span>${u.phone}</span></div><div><label>注册时间</label><span>${u.registered}</span></div><div><label>账号状态</label>${tag(u.status)}</div><div><label>累计登记</label><span>${u.records} 次</span></div><div><label>异常记录</label><span>${u.abnormal} 次</span></div></div></section><section class="detail-card full"><h3>最近业务记录</h3><div class="timeline"><div class="timeline-item"><span class="timeline-mark"></span><div><b>提交运送登记</b><p>${u.last} · 小程序</p></div></div><div class="timeline-item"><span class="timeline-mark"></span><div><b>规则自动检查完成</b><p>照片、定位及区域围栏校验</p></div></div></div></section></div></div><div class="drawer-footer"><button class="ghost-button" data-action="close-drawer">关闭</button><button class="button ${u.status==='正常'?'danger':''}" data-action="user-toggle" data-id="${u.id}">${u.status==='正常'?'封禁用户':'解除封禁'}</button></div>`);
    }
    if(a==='user-toggle'){
      const u=D.users.find(x=>x.id===t.dataset.id);const banning=u.status==='正常';
      confirmModal(banning?'封禁用户':'解除用户封禁',banning?`<div class="confirm-note">封禁后该用户不能发起新登记，尚未核销的处置码同步作废，历史记录继续保留。</div><div class="field"><label>封禁原因</label><textarea class="textarea" id="ban-reason" placeholder="填写封禁原因"></textarea></div>`:'<div class="field"><label>解封说明</label><textarea class="textarea" placeholder="填写解封说明"></textarea></div>',banning?'确认封禁':'确认解封','confirm-user-toggle',banning?'danger':'');
    }
    if(a==='confirm-user-toggle'){closeModal();closeDrawer();toast('用户账号状态已模拟更新');}
    if(a==='save-permissions')confirmModal('保存角色权限','<p>保存后新的菜单、操作和数据范围将立即对后台账号生效，变更内容会写入操作日志。</p>','确认保存','confirm-permissions');
    if(a==='confirm-permissions'){closeModal();toast('角色权限配置已模拟保存');}
    if(a==='save-settings')confirmModal('保存业务规则','<div class="confirm-note">规则仅对保存后新提交的登记生效，不追溯修改历史业务记录。</div><div class="field"><label>变更说明</label><textarea class="textarea" placeholder="填写本次规则变更说明"></textarea></div>','保存并生效','confirm-settings');
    if(a==='confirm-settings'){closeModal();toast('业务规则已模拟保存并生效');}
    if(a==='mock-search')toast('查询条件已应用');
    if(a==='show-help')openModal(`<div class="modal-header"><h2>原型使用说明</h2><button class="icon-button" data-action="close-modal">${icons.close}</button></div><div class="modal-content"><p>本原型演示三种后台角色差异，以及运送登记、照片定位审核、处置码、延期审批和核销记录闭环。</p></div><div class="modal-footer"><button class="button" data-action="close-modal">知道了</button></div>`);
    if(a==='show-notifications')toast('4 条业务通知：3 条延期审批，1 条高风险审核');
  });
  $('#role-select').addEventListener('change',e=>{S.role=e.target.value;S.page='dashboard';render();toast(`已切换为${D.roles[S.role].name}视角`)});
  $('#drawer-mask').addEventListener('click',e=>{if(e.target.id==='drawer-mask')closeDrawer()});$('#modal-mask').addEventListener('click',e=>{if(e.target.id==='modal-mask')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();closeModal()}});
  render();
})();
